from sqlalchemy.orm import Session
from app.models.interest import Interest
from app.models.job import Job
from app.models.user import User


def apply_job(db: Session, job_id: int, user_id: int):
    interest = Interest(
        job_id=job_id,
        job_seeker_id=user_id
    )#creating an interest object with the job id and user id ir equivalent to inserting data to a table

    db.add(interest)#add the interest object to the database session
    db.commit()#commit the transaction to save the interest in the database commit is permanent
    db.refresh(interest)#its lika token of assurance that the interest object is now updated with the id and created_at values generated by the database

    job = db.query(Job).filter(Job.id == job_id).first()

    return interest, job.google_form_link

def get_applicants_for_recruiter(db: Session, recruiter_id: int):
    return (
        db.query(Interest, User, Job)
        .join(Job, Job.id == Interest.job_id)
        .join(User, User.id == Interest.job_seeker_id)
        .filter(Job.recruiter_id == recruiter_id)
        .all()
    )